server:
  host: 0.0.0.0
  port: 9091

authentication_backend:
  file:
    path: /config/users.yml

access_control:
  default_policy: deny
  rules:
  - domain: yourdomain.com
    resources:
    - url: ^.*$
      methods:
      - GET
      - POST
      - PUT
      - DELETE
    subjects:
    - user: your_user_name
      groups:
      - your_group_name

session:
  secret: your_session_secret
  domain: yourdomain.com
  inactivity: 1h
  expiration: 24h

regulation:
  max_retries: 5
  find_time: 1m
  ban_time: 5m