services:
  swag:
    image: linuxserver/swag
    container_name: swag
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./config/swag:/config
      - ./data/swag:/data
    environment:
      - URL=dummy  # Use a dummy value like 'dummy' or 'example.com'
      - VALIDATION=http # Use HTTP validation (no certs needed initially)
      - CERTPROVIDER= # Leave empty to disable cert provisioning
      - ONLY_SUBDOMAINS=false
      - STAGING=false
      - EXTRA_DOMAINS=
    networks:
      - proxy

  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ./config/authelia:/config
    environment:
      - TZ=Europe/Helsinki
    depends_on:
      - swag

  kipa:
    container_name: kipa
    build: 
      context: ./kipa
      dockerfile: Dockerfile
    volumes:
      - ./kipa/kiba.db:/tmp/kipa.db
    depends_on:
      - authelia

networks:
  proxy:
    #external: true